#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --job-name=CLIPD-CIFAR10
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=00:15:00
#SBATCH --mem=32000M
#SBATCH --output=slurm_output_dp_test_inject_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

# activate the environment
source activate dl2023

# Run 1: Visual prompting CLIP on CIFAR-10 with standard text prompt
code_dir=./

## Set of experiments on CIFAR-10
#dataset="cifar10" # cifar100) fixed_patch
root=/scratch-local/$USER
mkdir -p $root

#python $code_dir/main.py --dataset cifar10 --prompt_type deep_prompt  --resume ./save/models/deep_prompt_fixed_patch_1_cifar10_clip_ViT-B/32_sgd_lr_40_decay_0_bsz_128_warmup_1000_trial_1/model_best.pth.tar --evaluate --root $root
#python $code_dir/main.py --dataset cifar100 --prompt_type deep_prompt  --resume ./save/models/deep_prompt_fixed_patch_1_cifar100_clip_ViT-B/32_sgd_lr_40_decay_0_bsz_128_warmup_1000_trial_1/model_best.pth.tar --evaluate --root $root


python $code_dir/main.py --dataset cifar10 --prompt_type deep_prompt  --resume ./save/models/deep_prompt_fixed_patch_1_cifar10_clip_ViT-B/32_sgd_lr_40_decay_0_bsz_128_warmup_1000_trial_1_injection_layer_5/model_best.pth.tar --evaluate --root $root --injection_layer 5
python $code_dir/main.py --dataset cifar100 --prompt_type deep_prompt  --resume ./save/models/deep_prompt_fixed_patch_1_cifar100_clip_ViT-B/32_sgd_lr_40_decay_0_bsz_128_warmup_1000_trial_1_injection_layer_5/model_best.pth.tar --evaluate --root $root --injection_layer 5
python $code_dir/main.py --dataset cifar10 --prompt_type deep_prompt  --resume ./save/models/deep_prompt_fixed_patch_1_cifar10_clip_ViT-B/32_sgd_lr_40_decay_0_bsz_128_warmup_1000_trial_1_injection_layer_10/model_best.pth.tar --evaluate --root $root --injection_layer 10
python $code_dir/main.py --dataset cifar100 --prompt_type deep_prompt  --resume ./save/models/deep_prompt_fixed_patch_1_cifar100_clip_ViT-B/32_sgd_lr_40_decay_0_bsz_128_warmup_1000_trial_1_injection_layer_10/model_best.pth.tar --evaluate --root $root --injection_layer 10